name: Documentation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

env:
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda.yaml
          channels: conda-forge,nodefaults
          activate-environment: fc-python
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.13"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry check
          poetry install --with dev --extras "dev"

      - name: Render Quarto site
        run: makim docs.build

      - name: Publish to gh-pages branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_site
          force_orphan: true
